# Generated by Django 4.2.5 on 2023-11-05 06:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firsts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=100)),
                ('emaill', models.EmailField(help_text='Please enter a valid email address', max_length=255, unique=True)),
                ('phonee', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('visit_datee', models.DateField()),
                ('how_heardd', models.CharField(max_length=100)),
                ('commentss', models.TextField()),
            ],
        ),
    ]
