# Generated by Django 4.2.5 on 2023-11-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_firsts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
    ]
