# Generated by Django 4.2.5 on 2023-11-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
